# Jekyll configuration

name: ScriptLife
description: Front End Developer

encoding: 'utf-8'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      author: 'uolcano'

# Url is currently only used only for the RSS feed in feed.xml
url: http://uolcano.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: '/blog-by-jekyll'

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: uolcano
#  stackoverflow: ''
#  linkedin:
#  instagram: ''
#  lastfm: ''
  codepen: uolcano
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-83553632-1
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica: 


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: UolCano
comments: true

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
paginate: 5

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']

gems: ['emoji_for_jekyll', 'jekyll-paginate']